#!/usr/bin/env bash

OPTIONS=(
     -sb 
     '#8a2be2'
     -shb
     '#ffd700'
     -shf
     '#342860'
     -nhf
     '#8a2be2'
     -nhb
     '#133337' 
     -h
     30
     -fn
     'NotoMonoRegular:regular:pixelsize=20'
 )

grep -v "#" ~/.scripts/unicode | dmenu -i -l 10 "${OPTIONS[@]}" | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard
