#!/usr/bin/env bash

# A script to display all the movies in the Movies folder of ntfs drive
# Whatever movie you select, it opens it with vlc

OPTIONS=("-sb" '#8a2be2' "-shb" '#ffd700' "-shf" '#342860' "-nhf" '#8a2be2' "-nhb" '#133337' "-h" "30" "-fn" 'NotoMonoRegular:regular:pixelsize=16')

du -a /mnt/ntfs/Movies/ | cut -f2- | grep -i "mkv$\|avi$\|mp4$" | dmenu -i -l 20 "${OPTIONS[@]}" | xargs -I {} vlc "{}"
